WIP Restructure Yupana to process metadata and report payloads
quipucords/yupana pull request #117
Opened 2019-05-02 22:00 UTC by abaiken

TODO: Fix texts 
TODO: update to match Kev's changes

2019-05-07 10:06 UTC, kholdaway requested changes

2019-05-07 12:00 UTC, kholdaway requested changes

2019-05-07 12:00 UTC, kholdaway commented on yupana/processor/abstract_processor.py
> +    def update_object_state(self, retry=RETRY.clear,   # noqa: C901 (too-complex)
Let's put all these parameters in an options object

2019-05-07 13:53 UTC, abaiken commented on yupana/api/report_slice/model.py
> +    state_info = models.TextField(null=True)
State info is JSON, so I think it should stay a TextField.

2019-05-07 16:58 UTC, kholdaway requested changes

2019-05-08 14:06 UTC, kholdaway approved these changes

2019-05-08 14:13 UTC, merged