WIP: Modify report processor to accept reports formatted to host inventory api spec
quipucords/yupana pull request #150
Opened 2019-06-06 18:20 UTC by abaiken

2019-06-07 11:02 UTC, kholdaway requested changes

2019-06-07 11:02 UTC, kholdaway commented on yupana/processor/abstract_processor.py
> +        for host in hosts:
Right before this, you should do a `if len(hosts) > MAX_ALLOWED` throw error.  This is ensuring that if their meta-data reported a different number we still toss it out.  We might even want to make sure the meta-data number matches but that's not required.  At a minimum printing a warning would be good so we can ensure they are the same.

2019-06-07 11:03 UTC, kholdaway commented
Looks good.  Added suggestion for validation additions.

2019-06-10 19:26 UTC, abaiken commented on yupana/processor/abstract_processor.py
> +        for host in hosts:
I moved this validation to the report processor in the `extract_and_create_slices method`.  I ensure that the hosts are less than the MAX_ALLOWED when validating the metadata, and then I ensure that the length matches what the metadata reported.

2019-06-11 14:06 UTC, myersCody requested changes

2019-06-11 14:13 UTC, abaiken commented on yupana/processor/tests_report_processor.py
> +            'source': 'qpc',
I will add one. The only thing it would change in the test is that the name length is fine to save in the source field.

2019-06-11 14:26 UTC, myersCody approved these changes
👍 Awesome work Ash

2019-06-11 17:47 UTC, kholdaway requested changes
Changes around 10000 value

2019-06-11 17:47 UTC, kholdaway commented on yupana/api/report_slice/serializer.py
> +    hosts_count = IntegerField(min_value=1, max_value=10000)
I would not set this as a static value of 10K.  We probably want to allow that to be configurable without a code change.  At a minimum, we should have a constant for the 10000 so we can change the code in a single place.

2019-06-11 17:47 UTC, kholdaway commented on yupana/api/migrations/0001_initial.py
> +                ('hosts_count', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)])),
Let's not bake the max into the DB.  Validation can handle that constraint.

2019-06-11 17:47 UTC, kholdaway commented on yupana/api/migrations/0001_initial.py
> +                ('hosts_count', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)])),
Let's not back this value into the database.  Changing it would require a migration.

2019-06-11 17:47 UTC, kholdaway commented on yupana/api/report_slice/model.py
> +        null=False, validators=[MinValueValidator(1), MaxValueValidator(10000)])
Use constant or env variable here for 10K

2019-06-13 12:49 UTC, abaiken commented on yupana/api/report_slice/model.py
> +        null=False, validators=[MinValueValidator(1), MaxValueValidator(10000)])
If we don't want to bake this value into the db, I should not put a max value here & only put a max constraint inside of the serializers.

2019-06-13 12:52 UTC, kholdaway commented on yupana/api/report_slice/model.py
> +        null=False, validators=[MinValueValidator(1), MaxValueValidator(10000)])
👍

2019-06-13 14:38 UTC, kholdaway approved these changes

2019-06-13 14:44 UTC, merged