Add flag for UPLOAD_MODE to the inventory
quipucords/yupana pull request #195
Opened 2019-06-25 17:09 UTC by abaiken

Closes #194

2019-06-26 19:42 UTC, kholdaway requested changes

2019-06-26 19:42 UTC, kholdaway commented on openshift/yupana-template.yaml
> +    upload-mode: ${UPLOAD_MODE}
Let's call this `HOST_INVENTORY_UPLOAD_MODE`

2019-06-26 19:53 UTC, abaiken commented on openshift/yupana-template.yaml
> +    upload-mode: ${UPLOAD_MODE}
👍 That is a better name.

2019-06-26 20:38 UTC, kholdaway approved these changes

2019-06-27 11:54 UTC, myersCody approved these changes

2019-06-27 12:09 UTC, merged