WIP: Scripts to bring up yupana with a single command
quipucords/yupana pull request #198
Opened 2019-06-25 21:34 UTC by kholdaway

Closes #184

2019-06-26 13:20 UTC, Dostonbek1 commented on README.md
> +This project is developed using the Django web framework. Many configuration settings can be read in from a `.env` file. An example file `.env.dev.example` is provided in the repository. To use the d
`simply *run*:` ?

2019-06-26 13:24 UTC, kholdaway commented on README.md
> +This project is developed using the Django web framework. Many configuration settings can be read in from a `.env` file. An example file `.env.dev.example` is provided in the repository. To use the d
👍

2019-06-26 14:52 UTC, myersCody commented on README.md
> +    ```
I think your ``` are off here. Supposed to be the closing one for 4

2019-06-26 15:33 UTC, abaiken requested changes

2019-06-26 15:33 UTC, abaiken commented on README.md
> +First, make sure you have no zombie docker containers that could conflict with the services you are bring up.  Run:
change `bring` to `bringing`

2019-06-26 15:33 UTC, abaiken commented on README.md
> +Make sure there are no docker containers that will conflict.  It is best to have none at all but if you know what you are doing you can leave some.
I would change this to say: `Make sure that there are no docker containers that will conflict with the services that are about to be brought up. It is safest if you have none at all, but containers that will not conflict can be left.`

2019-06-26 15:33 UTC, abaiken commented on README.md
> +To locally run the file upload service, yupana, and host inventory service run the following command:
Change this to say: `To run the file upload service, yupana, and host inventory service locally, use the following command: `

2019-06-26 15:33 UTC, abaiken commented on README.md
> +You will need to wait for the services to come up (this can take some time).  Once you think they are up run:
Change `Once you think they are up run:` to `To check if the services are up, run:`

2019-06-26 15:33 UTC, abaiken commented on README.md
> +The `/etc/hosts` file must be updated for Kafka and Minio.  Open your `/etc/hosts` file and add these lines to the end.
Change `add these lines to the end` to `add the following lines to the end:`

2019-06-26 15:33 UTC, abaiken commented on README.md
> +This project is developed using the Django web framework. Many configuration settings can be read in from a `.env` file. An example file `.env.dev.example` is provided in the repository. To use the d
Should we say anything about the external env file? Possibly in the sending data to yupana section?

2019-06-26 21:39 UTC, abaiken commented on README.md
> +Once you think they are up run: to To check if the services are up, run:
I think you misunderstood my comment here. The above makes no sense. Go back and look at what I said.

2019-06-26 21:53 UTC, myersCody approved these changes
The test scenario is consistently working for me now. Address comments on docs and I think you are good to go.

2019-06-27 12:10 UTC, abaiken commented on .env.dev.example
> +EMPTY_QUEUE_SLEEP=10
rename this to `NEW_REPORT_QUERY_INTERVAL`

2019-06-27 15:11 UTC, abaiken approved these changes
This is awesome 👍

2019-06-27 15:14 UTC, merged