WIP: Use Kafka to upload hosts to inventory
quipucords/yupana pull request #216
Opened 2019-07-16 17:48 UTC by abaiken

Closes #209

2019-07-19 19:56 UTC, kholdaway commented on yupana/processor/report_slice_processor.py
> +HOSTS_PER_REQ = int(HOSTS_PER_REQ)
Do you need this?

2019-07-19 19:56 UTC, kholdaway commented on yupana/processor/report_slice_processor.py
> +MAX_THREADS = int(MAX_THREADS)
Do you need this?

2019-07-19 19:56 UTC, kholdaway commented on yupana/processor/report_slice_processor.py
> +INVENTORY_FAILURE = 'INVENTORY FAILURE'
Do you need this?

2019-07-19 19:57 UTC, kholdaway commented on yupana/processor/report_slice_processor.py
> +UPLOAD_DATA_FAILURE = 'UPLOAD DATA FAILURE'
Do you need this?

2019-07-19 20:03 UTC, kholdaway commented on yupana/processor/report_slice_processor.py
> +    def record_inventory_upload_errors(self, options):
Let's remove this since we get no validation feedback

2019-07-19 20:16 UTC, kholdaway requested changes
Looks great!

2019-07-19 20:16 UTC, kholdaway commented on yupana/processor/report_slice_processor.py
> +                LOG.info(
Let's move this down inside the if statement.

2019-07-19 20:16 UTC, kholdaway commented on yupana/processor/report_slice_processor.py
> +                if count % 100 == 0 or count == total_hosts:
Let's make the 100 an environment variable so that we can tweak values.

2019-07-19 20:16 UTC, kholdaway commented on yupana/processor/report_slice_processor.py
> +                        await asyncio.wait(send_futures, timeout=5)
let's make the 5 a 60 or 120.

2019-07-23 03:08 UTC, abaiken commented on yupana/processor/report_slice_processor.py
> +UPLOAD_DATA_FAILURE = 'UPLOAD DATA FAILURE'
Removed all unnecessary variables.

2019-07-29 20:47 UTC, kholdaway approved these changes

2019-07-29 21:14 UTC, merged