WIP: Stop processors when fatal errors occur
quipucords/yupana pull request #252
Opened 2019-09-26 22:19 UTC by abaiken

Closes #251

2019-10-02 22:23 UTC, myersCody approved these changes

2019-10-03 21:59 UTC, kholdaway requested changes

2019-10-03 21:59 UTC, kholdaway commented on yupana/processor/report_consumer.py
> +            if isinstance(i, ReportConsumer):
I would move the try/catch to a method that wraps the stop calls so that one failure doesn't prevent the loop from continuing.

2019-10-03 22:01 UTC, kholdaway commented on yupana/processor/report_consumer.py
> +PROCESSOR_INSTANCES = []  # this list holds processor instances that have kafka components
This warrants a comment since the list is modified by 3 threads and many languages won't ensure consistency cross thread.  Yay python!  http://effbot.org/pyfaq/what-kinds-of-global-value-mutation-are-thread-safe.htm

2019-10-03 22:09 UTC, kholdaway commented on yupana/processor/report_consumer.py
> +GARBAGE_COLLECTION_LOOP = asyncio.new_event_loop()
This seems a little confusing in terms of location.  Can we move these out to an independent module?

2019-10-03 22:10 UTC, kholdaway commented on yupana/processor/report_consumer.py
> +def stop_all_event_loops():
This also could live in an independent module

2019-10-06 23:33 UTC, abaiken commented on yupana/processor/report_consumer.py
> +PROCESSOR_INSTANCES = []  # this list holds processor instances that have kafka components
Noted 👍

2019-10-06 23:33 UTC, abaiken commented on yupana/processor/report_consumer.py
> +GARBAGE_COLLECTION_LOOP = asyncio.new_event_loop()
Fixed.

2019-10-06 23:33 UTC, abaiken commented on yupana/processor/report_consumer.py
> +def stop_all_event_loops():
Fixed.

2019-10-07 12:48 UTC, abaiken commented on yupana/processor/report_consumer.py
> +            if isinstance(i, ReportConsumer):
Fixed.

2019-10-07 17:49 UTC, myersCody commented
I retested the critical error using the methods used in the description and it worked for me! 👍

2019-10-08 13:17 UTC, kholdaway approved these changes
Looks good

2019-10-08 13:26 UTC, myersCody approved these changes

2019-10-08 16:48 UTC, merged