fixes #5 - transform os_release & add tag with NS 'yupana' to host
quipucords/yupana pull request #323
Opened 2020-09-18 15:01 UTC by kgaikwad

Pushing an initial attempt related to os_release field parsing. I will add tests cases.

With this change, parsing an os_release field of each host into name, version, code using regular expression before it publishes kafka message for inventory.
Updating existing `os_release` with version value & adding new tag entry with namespace called `yupana` with key as `os_name` and value as `name` from parsing output of os_release.

2020-09-21 12:31 UTC, beav commented on yupana/processor/report_slice_processor.py
> +                    host['tags'].append({
Is the "os_name" tag needed?

2020-09-21 14:29 UTC, kholdaway commented on yupana/processor/report_slice_processor.py
> +                if 'system_profile' in host and 'os_release' in host['system_profile'].keys():
I think system_profile set to `None` will cause an issue here.  You should think about defaulting it to avoid that.  

```
if 'os_release' in host.get('system_profile', {})
```

2020-09-21 16:06 UTC, abaiken commented on yupana/processor/report_slice_processor.py
> +            match_obj
if you are trying to return `match_obj` from this function, you need to change this to `return match_obj`  otherwise I think it returns None

2020-09-21 16:07 UTC, kholdaway commented
It looks like travis tests are not passing.  You have lint errors.  You can run those locally to fix them (see the README).  I would make sure you have tested end to end with a local development environment.

2020-09-21 17:39 UTC, kholdaway commented
I recommend adding unit tests.

2020-09-21 17:59 UTC, kholdaway commented on yupana/processor/report_slice_processor.py
> +            match_obj
Ashley is correct.  `parse_os_release_field` will always return `None` due to the missing return statement.  I think other languages behave differently but python requires the return statement.

2020-09-22 06:45 UTC, kgaikwad commented on yupana/processor/report_slice_processor.py
> +            match_obj
Good Catch @abaiken :+1:  
I should avoid last moment refactoring :)

> I think other languages behave differently but python requires the return statement.
yes!

2020-09-22 06:48 UTC, kgaikwad commented on yupana/processor/report_slice_processor.py
> +                    host['tags'].append({
Yes, it would be good to have new tag as `os_release` includes not only RHEL but also other OS names.
With the help of this tag, it would be easy to filter hosts list as per the tag's value wherever required.

2020-09-22 11:00 UTC, kgaikwad commented
@beav,  @kholdaway, @abaiken,

Thank you for review. 
I liked the @Josca's approach of having constant which allow enabling or disabling parsing for host's fields.
Pulled his commits from opened PR and added modifications in code & tests changes on top of it.
Along with `os_release`, now with these changes it will also parse `os_kernel_version`.
Please feel free to add suggestions.

2020-09-22 14:12 UTC, beav commented on yupana/processor/report_slice_processor.py
> +                    host['tags'].append({
I would leave this out for now. The `os_name` should probably live in the system profile itself and not in the tags, but it will require additional coordination with other teams to add it.

2020-09-22 15:11 UTC, ShimShtein commented on yupana/processor/report_slice_processor.py
> +                    host['tags'].append({
@beav, that's exactly the reason I asked Kavita to add it here. We need a way to query the inventory based on RHEL - non-RHEL division. Basically there are services that assume we have only RHEL hosts in the inventory, so we need to provide them with an ability to filter out non-RHEL hosts. If I look at the API, the only way to filter records is based on tags, hence the `os_name` tag.

2020-09-24 17:53 UTC, beav commented on yupana/processor/report_slice_processor.py
> +                    host['tags'].append({
thanks for splitting it out!

2020-09-28 15:31 UTC, abaiken reviewed
This LGTM 👍  You will want to have someone from your team approve.

2020-09-28 15:31 UTC, abaiken commented on yupana/config/settings/base.py
> +HOSTS_TRANSFORMATION_ENABLED = ENVIRONMENT.bool('HOSTS_TRANSFORMATION_ENABLED', default=True)
In order to be able to toggle this, you will have to add it to the templates for yupana in the e2e-repo https://github.com/RedHatInsights/e2e-deploy/blob/6676500d7c6420f6c5dd3b0bb5e9cd77ec244b83/templates/subscriptions/configmap.yml

2020-09-28 16:33 UTC, kgaikwad commented on yupana/config/settings/base.py
> +HOSTS_TRANSFORMATION_ENABLED = ENVIRONMENT.bool('HOSTS_TRANSFORMATION_ENABLED', default=True)
Just to confirm - is this a private repository as on hitting above URL I am getting `404`?

2020-09-28 16:48 UTC, kgaikwad commented
> This LGTM +1 You will want to have someone from your team approve.

Thank you @abaiken for review. Fixed Codecov now its green.
@apuntamb, @beav, as you guys having a local dev setup up and running :)
Please feel free to add your review on updated changes.

2020-09-28 18:20 UTC, abaiken commented on yupana/config/settings/base.py
> +HOSTS_TRANSFORMATION_ENABLED = ENVIRONMENT.bool('HOSTS_TRANSFORMATION_ENABLED', default=True)
@kgaikwad Yes it is a private repository.

2020-09-29 06:59 UTC, apuntamb reviewed
Thanks for the PR @kgaikwad !
I tested it on my local development setup as follows:
1.  With HOSTS_TRANSFORMATION_ENABLED=false, it keeps the value of both fields as is.
2.  Without any env variable set, it transforms them to the expected values e.g. `"os_release": "8.0", "os_kernel_version": "4.18.0"`.

2020-09-29 11:51 UTC, ShimShtein requested changes

2020-09-29 11:51 UTC, ShimShtein commented on yupana/processor/abstract_processor.py
> +    def _transform_os_release(self, host: dict):
I suppose the transformation should  be done inside a slice, not for the whole report.
I think if we transform all records in memory, it would be very resource-consuming.

I suggest moving the transformation code into slice and invoking it after validation and before writing the host into kafka. I suppose it should live after the candidate selection: https://github.com/quipucords/yupana/blob/master/yupana/processor/report_slice_processor.py#L149

2020-09-29 11:51 UTC, ShimShtein commented on yupana/processor/tests_report_processor.py
> +            [{'123': {'system_profile': {'os_release': ''}}}])
I suppose it would be better not to report `os_release` fact at all in this case.

2020-09-29 12:17 UTC, kgaikwad commented on yupana/processor/abstract_processor.py
> +    def _transform_os_release(self, host: dict):
I do agree on resource-consuming and that's why initially I have added logic just before publishing kafka message `add_host` for inventory. In that way, I don't have to iterate again on hosts list.
[https://github.com/quipucords/yupana/blob/master/yupana/processor/report_slice_processor.py#L224](https://github.com/quipucords/yupana/blob/master/yupana/processor/report_slice_processor.py#L224)

I went through PR #322 opened by @Josca and thought it would be good to do parsing or any sort of transformation before validation so that even in future if any schema format changes on HBI side then it will fail at validation stage only.

2020-10-01 09:10 UTC, kgaikwad commented on yupana/processor/tests_report_processor.py
> +            [{'123': {'system_profile': {'os_release': ''}}}])
Done!

2020-10-01 12:07 UTC, kgaikwad commented on yupana/processor/abstract_processor.py
> +    def _transform_os_release(self, host: dict):
> https://github.com/quipucords/yupana/blob/master/yupana/processor/report_slice_processor.py#L224

@ShimShtein, is that okay if I move logic here in report slice processor? In this case we don't have to iterate list again?

2020-10-01 18:50 UTC, kgaikwad commented on yupana/processor/abstract_processor.py
> +    def _transform_os_release(self, host: dict):
Moved the parsing logic to report slice processor file.

2020-10-04 13:22 UTC, ShimShtein requested changes

2020-10-04 13:22 UTC, ShimShtein commented on yupana/processor/abstract_processor.py
> +    def _transform_os_release(self, host: dict):
> Moved the parsing logic to report slice processor file.

:+1: Awesome. I still think that the whole `_transform_os_release` should move to slice_processor. This method is not useful for other processors. The same goes for `_transform_os_kernel` method too.

2020-10-05 08:23 UTC, kgaikwad commented on yupana/processor/abstract_processor.py
> +    def _transform_os_release(self, host: dict):
Done!

2020-10-05 08:25 UTC, kgaikwad commented
Updated the changes as per suggestions. @apuntamb, please request to review & retest the scenario with updates changes.

2020-10-05 08:29 UTC, apuntamb commented
> Updated the changes as per suggestions.
> @apuntamb, please request to review & retest the scenario with updates changes.

Sure, on it! Reading the changes. :)

2020-10-05 14:38 UTC, kgaikwad commented
@ShimShtein, 
Updated the pull-request changes. 
With current changes it will also remove fact `os_release` in case of value ` ()` and fix codecov failures.
Please request to review updated changes.

2020-10-06 11:33 UTC, beav commented on yupana/processor/report_slice_processor.py
> +        if 'os_release' in host['system_profile'].keys():
the `.keys()` is implied by the `in` check and not needed here. For example:

```
In [1]: mydict = {}

In [2]: mydict['mykey'] = {'mykey2': 'myvalue2', 'mykey3': 'myvalue3'}

In [3]: mydict['mykey'].keys()
Out[3]: dict_keys(['mykey2', 'mykey3'])

In [4]: 'mykey' in mydict['mykey'].keys()
Out[4]: False

In [5]: 'mykey2' in mydict['mykey'].keys()
Out[5]: True

In [6]: 'mykey2' in mydict['mykey']
Out[6]: True

In [7]: 'mykey' in mydict['mykey']
Out[7]: False
```

2020-10-06 12:01 UTC, kgaikwad commented on yupana/processor/report_slice_processor.py
> +        if 'os_release' in host['system_profile'].keys():
Removed `.keys()` method call in condition.

2020-10-11 19:26 UTC, ShimShtein requested changes
Looking good, although I prefer less nesting, comments inline.

2020-10-11 19:26 UTC, ShimShtein commented on yupana/processor/report_slice_processor.py
> +                if os_release and os_release.strip():
Maybe it's worth consolidating the deletion cases:

```python
  source_os_release = os_release.strip() or ''
  # now we are sure source_os_release is always a string
  match_result = OS_RELEASE_PATTERN.match(source_os_release)
  parsed_info = match_result.groupdict()
  os_version = parsed_info['version'].strip()
  if not os_version:
    del host['system_profile']['os_release']
    LOG.info(
            format_message(
                    self.prefix,
                    'Removed empty os_release fact',
                    account_number=self.account_number,
                    report_platform_id=self.report_platform_id)
            )
    return host
  if os_version == os_release
    return host
  host['system_profile']['os_release'] = os_version
  LOG.info(
          format_message(
                 self.prefix,
                 "os_release transformed '%s' -> '%s'"
                 % (os_release, os_version),
                 account_number=self.account_number,
                 report_platform_id=self.report_platform_id)
  )
  return host
```

IMHO it's a bit more readable, maybe even worth splitting into a bit smaller methods.

2020-10-11 19:26 UTC, ShimShtein commented on yupana/processor/report_slice_processor.py
> +        if isinstance(os_kernel_version, str) and os_kernel_version:
Short circuiting here too?

```suggestion
        if not (isinstance(os_kernel_version, str) and os_kernel_version):
          return host
```

2020-10-12 11:00 UTC, kgaikwad commented on yupana/processor/report_slice_processor.py
> +                if os_release and os_release.strip():
@ShimShtein,
Consolidated both deletion cases by extracting out parsing logic using regular expression to new method.
Please request to review updated changes.

2020-10-12 12:58 UTC, kgaikwad commented
@apuntamb, finally flake8 lint warnings are resolved. Please request to test updated changes.

2020-10-12 13:20 UTC, apuntamb approved these changes
Reviewed and tested in my local environment. Works as expected @kgaikwad . :+1:

2020-10-12 13:28 UTC, apuntamb commented
@ShimShtein the PR looks green overall, could you give an ACK before I merge it? :)

2020-10-12 13:51 UTC, ShimShtein requested changes

2020-10-12 13:51 UTC, ShimShtein commented on yupana/processor/report_slice_processor.py
> +        os_release = host['system_profile']['os_release']
```suggestion
        os_release = host['system_profile'].get('os_release')
        if not isinstance(os_release, str):
            return host
```

`get` will not throw an exception, and `isinstance` will return false if the value is Nothing

2020-10-12 13:51 UTC, ShimShtein commented on yupana/processor/report_slice_processor.py
> +        os_key_present = 'os_release' in host['system_profile']
We probably need to code defensively against non-existing `system_profile` here too:

``` python
system_profile = host.get('system_profile', {})
```

2020-10-12 13:51 UTC, ShimShtein commented on yupana/processor/report_slice_processor.py
> +        if not (isinstance(os_kernel_version, str) and os_kernel_version):
`os_kernel_version` will always be `str`, since you pass a default empty string to `get`. 
You probably want to remove the default value from get and then you can leave only `not isinstance` in the `if` statement

2020-10-12 13:51 UTC, ShimShtein commented on yupana/processor/report_slice_processor.py
> +
Empty line not needed?

2020-10-12 16:39 UTC, kgaikwad commented on yupana/processor/report_slice_processor.py
> +
Removed it.

2020-10-13 07:15 UTC, ShimShtein approved these changes
ACK from me

2020-10-13 09:37 UTC, merged

2020-10-13 09:37 UTC, apuntamb commented
Merged, thanks @kgaikwad !