Avoid processing older reports
quipucords/yupana pull request #327
Opened 2020-10-01 14:17 UTC by patilsuraj767

With this PR report_consumer will check the expiry of minio url and will not process the report if the link is expired.

2020-10-06 18:02 UTC, beav commented on yupana/processor/report_consumer.py
> +        expire_time = timedelta(seconds=int(parsed_url_query['X-Amz-Expires'][0]))
does this parse as expected? In the value below, `X-Amz-Expires` is an iso8601 date (`20200930T063623Z`), but it looks like you are casting to `int`. You may need to read the iso8601 date and then calculate its expired time from that.

2020-10-06 18:04 UTC, beav commented on yupana/processor/report_consumer.py
> +        creation_datatime = datetime.strptime(str(creation_timestamp[0]), '%Y%m%dT%H%M%SZ')
https://docs.python.org/3/library/datetime.html#datetime.datetime.fromisoformat may work here to parse the datetime

2020-10-07 06:06 UTC, patilsuraj767 commented on yupana/processor/report_consumer.py
> +        creation_datatime = datetime.strptime(str(creation_timestamp[0]), '%Y%m%dT%H%M%SZ')
> https://docs.python.org/3/library/datetime.html#datetime.datetime.fromisoformat may work here to parse the datetime

Thanks Chris for reviewing the PR.  I have gone through the above doc link but it is of python3.9 and yupana runs on python3.6. Unfortunately 3.6 does not have `fromisoformat` method in `datetime`.

2020-10-11 19:43 UTC, ShimShtein requested changes

2020-10-11 19:43 UTC, ShimShtein commented on yupana/processor/report_consumer.py
> +                format_message(self.prefix, 'Can not process reports older than %s.' % expire_time))
IMHO the message is a bit misleading: the method checks against two parameters set by the framework on the message.
Theoretically you can have one message that is sent in `t0` with expiration set to `+10s` and another message that is sent in `t1=t0+5` and expiration set to `+1s` if you process both on `t2=t0+7`, you will have first message pass, but second message will tell you that `"the system cannot process messages older than 1 second"`.

Personally I would prefer something like `message <id> is already expired, and cannot be processed: <creation_time>, <expiry_interval>`

2020-10-11 19:43 UTC, ShimShtein commented on yupana/processor/tests_report_consumer.py
> +            mock_date.now.return_value = datetime(2020, 9, 30, 10, 36, 23)
Maybe instead of mocking system function, it would be better to generate payload URL according to current date?

2020-10-12 09:49 UTC, patilsuraj767 commented on yupana/processor/report_consumer.py
> +                format_message(self.prefix, 'Can not process reports older than %s.' % expire_time))
Thank you Shim for reviewing the PR, I have done the modification and changed the error message.

2020-10-12 09:51 UTC, patilsuraj767 commented on yupana/processor/tests_report_consumer.py
> +            mock_date.now.return_value = datetime(2020, 9, 30, 10, 36, 23)
Modified the test case to generate URL according to the current date.

2020-10-12 11:13 UTC, ShimShtein commented
ACK from me, although this needs a rebase.

2020-10-21 08:15 UTC, ShimShtein approved these changes
ACK from me, although not tested.

2020-11-26 10:26 UTC, kgaikwad requested changes
@patilsuraj767,
Tested the changes by modifying `X-Amz-Date` in message format & under yupana logs, I can see log messages for expired reports.  
Could you rebase the branch? Also, added small inline comment.

2020-11-26 12:09 UTC, kgaikwad approved these changes

2020-11-26 12:13 UTC, merged

2020-11-26 12:13 UTC, kgaikwad commented
Thanks @patilsuraj767!