Remove ip_addrs & mac_addrs fields if empty
quipucords/yupana pull request #328
Opened 2020-10-08 09:32 UTC by apuntamb

The hypervisor has empty arrays in `ip_addresses` and `mac_addresses` fields. This will fail validation on the inventory side and prevent the host record from appearing there. This has been handled already in the `foreman_rh_cloud` plugin under [foreman_rh_cloud/pull/249](https://github.com/theforeman/foreman_rh_cloud/pull/249). This PR removes both these fields when they have empty arrays as values.
The PR needs a rebase on top of [yupana/pull/323](https://github.com/quipucords/yupana/pull/323/files) once it's merged and I could then include these method calls in [_transform_single_host](https://github.com/quipucords/yupana/pull/323/files#diff-f049d03813e04872b2e244ca395a9aaaR269).

2020-10-14 10:22 UTC, patilsuraj767 commented
Tested pull-request changes on my local setup. Working as expected :+1:

2020-10-14 15:38 UTC, kgaikwad requested changes
Added few inline comments.

2020-10-14 15:38 UTC, kgaikwad commented on yupana/processor/report_slice_processor.py
> +    def _remove_ip_addresses(self, host: dict):
One can be confused by an existing method name as this method only removes `ip_addresses` key only when contains empty array or nothing.

```suggestion
    def _remove_empty_ip_addresses(self, host: dict):
```

2020-10-14 15:38 UTC, kgaikwad commented on yupana/processor/report_slice_processor.py
> +        return host
```suggestion
        ip_addresses = host.get('ip_addresses')
        if ip_addresses is None or ip_addresses:
            return host

        del host['ip_addresses']
        LOG.info(
            format_message(
                self.prefix,
                'Removed empty ip_addresses fact.',
                account_number=self.account_number,
                report_platform_id=self.report_platform_id
            ))
        return host
```
What do you think?

2020-10-14 15:38 UTC, kgaikwad commented on yupana/processor/report_slice_processor.py
> +    def _remove_mac_addresses(self, host: dict):
ditto

2020-10-14 15:50 UTC, ShimShtein requested changes

2020-10-14 15:50 UTC, ShimShtein commented on yupana/processor/report_slice_processor.py
> +        if 'mac_addresses' in host:
Worth refactoring to short circuit, like the `ip_addresses` method.

2020-10-14 17:11 UTC, apuntamb commented on yupana/processor/report_slice_processor.py
> +        return host
Thanks for reviewing @kgaikwad and @ShimShtein!
Why are we checking `if ip_addresses is None or ip_addresses` as one? Aren't they contradicting? Or am I missing something? I am guessing `ip_addresses is None` will give `false` even when the array will be empty [].
Sharing what I could try on a Python Interpreter:
``` python
>>> k = {'a': ['h']}
>>> b = k.get('a')
>>> b is None """output False as b = ['h']"""
>>> k = {'a': []}
>>> b = k.get('a')
>>> b is None  """output False as b = []"""
```
Thoughts?

2020-10-14 18:09 UTC, kgaikwad commented on yupana/processor/report_slice_processor.py
> +        return host
@apuntamb,

As per my understanding, 
it should delete `ip_addresses` key when ip_addresses contains empty array i.e `host={'ip_addresses': []}` and 
for host values like `host={'ip_addresses': ['192.168.10.10']} or host={}`, it shouldn't execute delete key action.
When `host={'ip_addresses': []}`, `if condition` block won't run. 

If you think it is contradicting, you can ignore it. It was just a suggestion. :)

2020-10-15 05:42 UTC, apuntamb commented on yupana/processor/report_slice_processor.py
> +        return host
@kgaikwad Your suggestion makes perfect sense. I think I didn't quite well catch up on the context of `None` here. Will apply these changes. :+1:

2020-10-15 06:13 UTC, apuntamb commented on yupana/processor/report_slice_processor.py
> +            host = self._remove_mac_addresses(host)
done

2020-10-15 06:13 UTC, apuntamb commented on yupana/processor/report_slice_processor.py
> +    def _remove_ip_addresses(self, host: dict):
done.

2020-10-15 06:13 UTC, apuntamb commented on yupana/processor/report_slice_processor.py
> +        return host
done.

2020-10-15 06:14 UTC, apuntamb commented on yupana/processor/report_slice_processor.py
> +        if 'mac_addresses' in host:
done.

2020-10-15 14:06 UTC, kgaikwad approved these changes
LGTM, thank you @apuntamb :+1: 
@ShimShtein, do you have any additional comments?

2020-10-21 08:00 UTC, ShimShtein commented on yupana/processor/tests_report_slice_processor.py
> +    def test_remove_empty_ip_addresses(self):
For completeness sake, I would also add test to check `None` values:

``` py
        """Test remove host ip_addresses."""
        host = {}
        host = self.processor._remove_empty_ip_addresses(host)
        host = self.processor.test_remove_empty_mac_addresses(host)
        self.assertEqual(host, {})
```

2020-10-27 09:54 UTC, apuntamb commented on yupana/processor/tests_report_slice_processor.py
> +    def test_remove_empty_ip_addresses(self):
done.

2020-10-28 10:09 UTC, apuntamb commented
@ShimShtein @kgaikwad how about one final round of review now?

2020-11-09 09:44 UTC, ShimShtein approved these changes
:+1: LGTM

2020-11-24 08:38 UTC, kgaikwad approved these changes

2020-11-24 08:43 UTC, merged

2020-11-24 08:43 UTC, kgaikwad commented
Thank you @apuntamb