fixes #17 - transform mtu value to interger
quipucords/yupana pull request #331
Opened 2020-11-06 07:36 UTC by kgaikwad

2020-11-09 08:04 UTC, apuntamb commented on yupana/processor/report_slice_processor.py
> +        if not network_interfaces:
can there be any case when `network_interfaces` key itself will be absent?

2020-11-09 08:17 UTC, ShimShtein reviewed
One small nitpick, but overall looks good.

2020-11-09 08:17 UTC, ShimShtein commented on yupana/processor/report_slice_processor.py
> +        if not network_interfaces:
I don't think that Satellite can produce such records, but I think yupana should be resilient to this anyway.
There is no need to throw an exception in this case.

2020-11-09 08:17 UTC, ShimShtein commented on yupana/processor/report_slice_processor.py
> +        host['system_profile']['network_interfaces'] = network_interfaces
Why do you need to reassign `network_interfaces`? It is passed by ref, does it not?

2020-11-09 15:47 UTC, kgaikwad commented on yupana/processor/report_slice_processor.py
> +        host['system_profile']['network_interfaces'] = network_interfaces
Good catch :+1: 
It's `dict` type so yes it is passed by reference. 
No need of reassignment, I will update PR.

2020-11-10 06:30 UTC, kgaikwad commented on yupana/processor/report_slice_processor.py
> +        host['system_profile']['network_interfaces'] = network_interfaces
done!

2020-11-10 18:10 UTC, ShimShtein requested changes
Small nitpick and we're done

2020-11-10 18:10 UTC, ShimShtein commented on yupana/processor/report_slice_processor.py
> +                mtu_transformed = True
2 things: We can remove the second `if` statement too and since the iterator also passes the same reference to a single item, we can reuse it and change the value in place:

```suggestion
        for nic in network_interfaces:
            if 'mtu' not in nic or not nic['mtu'] or isinstance(nic['mtu'], int):
                continue

                nic['mtu'] = int(nic['mtu'])
                mtu_transformed = True
```

2020-11-11 11:57 UTC, kgaikwad commented on yupana/processor/report_slice_processor.py
> +                mtu_transformed = True
:+1:   that makes sense!

2020-11-25 11:38 UTC, apuntamb approved these changes

2020-11-25 11:39 UTC, merged

2020-11-25 11:39 UTC, apuntamb commented
Merged, thanks @kgaikwad!