fixes #21 - add OS major/minor/name to yupana
quipucords/yupana pull request #333
Opened 2020-11-19 04:07 UTC by patilsuraj767

2020-11-19 13:02 UTC, ShimShtein requested changes
I suppose it would be easier to change the original regex and parse the OS name and major - minor parts from there directly.

2020-12-14 08:34 UTC, kgaikwad requested changes
@patilsuraj767,
As @ShimShtein mentioned, you can make use of an existing `os-release` regex.
Please verify & test below regex if that is helpful to you to add suggested changes related major/minor versions:

`re.compile(r'(?P<name>[a-zA-Z\s]*)?\s*((?P<major>\d+)(\.(?P<minor>\d+)(\.(?P<patch>\d+))?)?)\s*(\((?P<code>\S*)\))?')`

2020-12-16 07:38 UTC, kgaikwad requested changes
@patilsuraj767, added few inline comments.

2020-12-16 07:38 UTC, kgaikwad commented on yupana/processor/report_slice_processor.py
> +            os_version['version'] = f"{os_version['major'].strip()}.{os_version['minor'].strip()}"
Using regex, it will return either digit values or empty strings in major, minor & patch. Do we still need to apply `strip` method here?

2020-12-16 07:38 UTC, kgaikwad commented on yupana/processor/report_slice_processor.py
> +            os_version['version'] = f"{os_version['major'].strip()}.{os_version['minor'].strip()}"
Could you move concatenation logic for `version` in  `_match_regex_and_find_version` method only?

2020-12-16 07:38 UTC, kgaikwad commented on yupana/processor/report_slice_processor.py
> +            host['system_profile']['operating_system']['minor'] = '0'
If it is required to be an integer field, could you shift this to `_match_regex_and_find_version` method?

2020-12-21 10:47 UTC, kgaikwad requested changes

2020-12-21 10:47 UTC, kgaikwad commented on yupana/processor/report_slice_processor.py
> +            host['system_profile']['operating_system']['name'] = os_details['name'].strip()
```suggestion
         host['system_profile']['operating_system'] = { 
        'major': os_details['major'], 
        'minor': os_details['minor'],
        'name':  ('RHEL' if 'Red Hat' in os_details['name'] else os_details['name']).strip() }
```

2020-12-22 14:08 UTC, ShimShtein requested changes

2020-12-22 14:08 UTC, ShimShtein commented on yupana/processor/tests_report_slice_processor.py
> +            'major': '7', 'minor': '0', 'name': 'CentOS Linux'}, 'os_release': '7'}})
I think according to the current schema this value of the `name` field will not be accepted: https://github.com/RedHatInsights/inventory-schemas/blob/5b2fad998ca46b2a5f8e7e314d8cc0577487b581/schemas/system_profile/v1.yaml#L200

2020-12-23 06:44 UTC, patilsuraj767 commented on yupana/processor/tests_report_slice_processor.py
> +            'major': '7', 'minor': '0', 'name': 'CentOS Linux'}, 'os_release': '7'}})
Yes, you are right. `maxLength` is 4.
Any suggestion regarding what should be the `name` for Non-RHEL OS?

2020-12-23 09:10 UTC, ShimShtein commented on yupana/processor/tests_report_slice_processor.py
> +            'major': '7', 'minor': '0', 'name': 'CentOS Linux'}, 'os_release': '7'}})
Since it's defined an enum with a single value `RHEL`, I think the field should be omitted, if it's a non-rhel host.

2020-12-28 09:21 UTC, kgaikwad commented on yupana/processor/tests_report_slice_processor.py
> +            'major': '7', 'minor': '0', 'name': 'CentOS Linux'}, 'os_release': '7'}})
@patilsuraj767, 
In case of non-rhel hosts, could you just omit `name` field from `operating_system` and not the whole `operating_system` key.
@ShimShtein, please correct me in case we will need to omit the `operating_system`  key itself.

2020-12-28 10:41 UTC, ShimShtein commented on yupana/processor/tests_report_slice_processor.py
> +            'major': '7', 'minor': '0', 'name': 'CentOS Linux'}, 'os_release': '7'}})
Agree with Kavita. I think omitting only name would be better in this case. As we discussed on IRC.

2020-12-29 05:50 UTC, kgaikwad approved these changes
Thank you @patilsuraj767.
Tested the changes. Works as expected. 
LGTM :+1: 

@ShimShtein, do you have any additional comments?

2020-12-29 10:11 UTC, kgaikwad commented
In the schema major and minor defined as integers, after passing string values (example - "7", "8") for major/minor getting a result through host API. That's why as per offline discussion, merging this PR.

2020-12-29 10:11 UTC, merged

2020-12-29 10:12 UTC, kgaikwad commented
Thank you @patilsuraj767 and @ShimShtein!