fixes #23 - Improve Liveness and Readiness checks
quipucords/yupana pull request #334
Opened 2020-11-23 09:05 UTC by patilsuraj767

With this PR in status API `/api/subscriptions/v1/status/` we will be checking if all the report processors/Threads are alive. 
If any of the report processor thread is exited then API will return 500 status code and liveness probe will get triggered.

2020-11-27 11:23 UTC, gnurag reviewed
Cosmetic suggestions.

2020-11-27 11:23 UTC, gnurag commented on yupana/api/status/view.py
> +    processor = list_name_of_processors()
Perhaps to avoid confusion, the name should be `processors` since it returns a list?

2020-12-01 08:38 UTC, kgaikwad requested changes
@patilsuraj767, LGTM :+1: 

Tested changes on local setup. 
When I stopped the processor's producer and respective loop, API `/api/subscriptions/v1/status/` returns 500 otherwise it is returning 200 OK.

Requested just small cosmetic changes.   Also, perform rebase.

2020-12-01 08:38 UTC, kgaikwad commented on yupana/api/status/view.py
> +    processors = list_name_of_processors()
```suggestion
    total_processors_names = list_name_of_processors()
```

2020-12-01 08:38 UTC, kgaikwad commented on yupana/api/status/view.py
> +    threads = list_name_of_active_threads()
```suggestion
    active_threads_names = list_name_of_active_threads()
```

2020-12-01 08:38 UTC, kgaikwad commented on yupana/api/status/view.py
> +        dead_threads = set(processors).difference(threads)
```suggestion
        dead_processors = set(total_processors_names).difference(active_threads_names)
```

2020-12-01 08:38 UTC, kgaikwad commented on yupana/api/status/view.py
> +        LOG.error(format_message('SERVICE STATUS', 'Dead processors - %s' % dead_threads))
```suggestion
        LOG.error(format_message('SERVICE STATUS', 'Dead processors - %s' % dead_processors))
```

2020-12-01 14:59 UTC, kgaikwad approved these changes
Thanks @patilsuraj767!

2020-12-01 15:12 UTC, merged