support reports with bzip2,xz compression including gz
quipucords/yupana pull request #336
Opened 2020-12-29 07:37 UTC by kgaikwad

Fixes - [YUPANA-27](https://projects.engineering.redhat.com/browse/YUPANA-27)

2020-12-30 11:11 UTC, ShimShtein approved these changes
LGTM

2020-12-30 13:45 UTC, apuntamb requested changes
Looks great! Will test it now locally. Just added one small inline comment.

2020-12-30 13:45 UTC, apuntamb commented on yupana/processor/tests_report_processor.py
> +    def test_extract_and_create_slices_success_using_bz2(self):
Can we add one more similar test case for `xz` compression too?
Also, might want to specify [line 894](https://github.com/quipucords/yupana/pull/336/files#diff-f2010242e5b432fcf8aac4fc931b3751f5c2ca68066904676e52ea7a1b70dd10R894) with test name containing `using gz` as it's no longer the only method of compression?

2020-12-31 08:54 UTC, apuntamb commented
Tested locally, works as expected!

2021-01-11 15:27 UTC, apuntamb approved these changes
Looks ready to get in as test failures are no longer occurring. :+1:

2021-01-11 15:45 UTC, kgaikwad commented
@apuntamb,
Weird! This test is irrelevant to the change but started failing against the PR & 
on master also I was getting the same test failure.  Could you confirm the test behaviour against master on your side?

Today while debugging on test failure, test passed on local for me but here it is still failing. 
I would suggest to merge this change & I will look into test failure separately as similar behaviour against master too.

2021-01-12 06:12 UTC, apuntamb commented
@kgaikwad I agree, but the tests are a Required Check for merging the PR and it won't allow me to merge until the check is green :(

2021-01-12 08:54 UTC, ShimShtein commented
@kgaikwad, sometimes the order of the tests is changing and causing random failures. Another thought: the failing test name implies you are testing an async action, maybe the action takes longer than expected?

2021-01-14 12:18 UTC, kgaikwad commented
@apuntamb @ShimShtein,
Test is failing at this line [L359](https://github.com/quipucords/yupana/blob/master/yupana/processor/tests_report_processor.py#L359).

On local somehow tests are green so I am facing difficulty in debugging the test failure. 
My assumption from test:
Initially, self.processor.report_platform_id is `None` after execution it expects that value matches with `self.report_record.report_platform_id`. 
Inside test, it gives call to method `await self.processor.delegate_state()` where it checks where processor's current state exists inside `state_functions` (key -> function mapping).
If it doesn't exist then it gives call to `reset_variables()` [here](https://github.com/quipucords/yupana/blob/0104dd097adc85765e7a570c77070dba50a0d06e/yupana/processor/abstract_processor.py#L133) 
Due to some delay, it fails to get `state` value from `processor` & results into `reset_variables()`. 
By adding small sleep test is passing now.

I understand this is very hacky way to fix the test but not getting how to fix such behavior. 
Please let me know your thoughts on it.

2021-01-14 12:25 UTC, apuntamb approved these changes
I guess for now, as a workaround, adding `sleep` would be ok.

2021-01-15 05:21 UTC, patilsuraj767 commented
Thank you @kgaikwad :+1: Merging this.

2021-01-15 05:21 UTC, merged