YUPANA-52 - transform tag's value to string
quipucords/yupana pull request #356
Opened 2021-07-21 11:01 UTC by kgaikwad

+ adding @ShimShtein into loop for review

2021-07-21 14:34 UTC, ShimShtein requested changes

2021-07-21 14:34 UTC, ShimShtein commented on yupana/processor/report_slice_processor.py
> +                format_message(
This will create a message per tag count. I think it should be outside the loop, or contain the tag that has been converted.

2021-07-22 08:27 UTC, kgaikwad commented on yupana/processor/report_slice_processor.py
> +                format_message(
:+1: Good catch! Moving outside of the loop.

2021-07-22 09:25 UTC, ShimShtein approved these changes
ACK from my side, looks good

2021-07-28 06:14 UTC, kgaikwad commented
@apuntamb, any additional comments from your side?

2021-07-28 08:33 UTC, apuntamb approved these changes
Looks good to me :+1:

2021-07-28 08:39 UTC, merged

2021-07-28 08:39 UTC, apuntamb commented
Merged, thanks @kgaikwad and @ShimShtein !