YUPANA 81- Remove installed_packages if kafka msg exceeds max_req_size
quipucords/yupana pull request #366
Opened 2021-12-14 15:46 UTC by apuntamb

2021-12-14 16:08 UTC, ShimShtein commented
@apuntamb we were also talking about adding custom tag for indicating this host as partial

2021-12-15 06:06 UTC, apuntamb commented
@ShimShtein @kgaikwad Do we want to update the existing `tags` [here](https://github.com/quipucords/yupana/blob/master/yupana/processor/report_slice_processor.py#L233) or add new key? Also, what do we want to set it to?

2021-12-15 07:53 UTC, ShimShtein commented
@apuntamb we need to add a new tag under a new namespace.
Personal vote would be: `{ namespace: 'report_preprocessor', key: 'packages_truncated', value: 'true' }`

2021-12-16 15:04 UTC, kgaikwad commented on yupana/processor/report_slice_processor.py
> +                        host['tags'].append(host_updated_tag)
These statements should be present outside of the `If` block.

2021-12-16 16:33 UTC, ShimShtein requested changes

2021-12-16 16:33 UTC, ShimShtein commented on yupana/processor/report_slice_processor.py
> +                        host['system_profile']['network_interfaces'] = list({
I think this should not be done only if the installed packages node is there

2021-12-17 07:20 UTC, apuntamb commented on yupana/processor/report_slice_processor.py
> +                    if host['system_profile']['network_interfaces']:
@ShimShtein @kgaikwad I missed checking presence of nics. This should make more sense.
Thoughts?

2021-12-17 10:06 UTC, kgaikwad requested changes

2021-12-17 10:08 UTC, kgaikwad commented
@apuntamb  - Could you please also look into error(s) in Github actions to make happy again!

2021-12-17 11:26 UTC, apuntamb commented
> @apuntamb - Could you please also look into error(s) in Github actions to make happy again!

@kgaikwad Yeah the current seems to be a linting error `Too many branches (16/12) (too-many-branches)` from the method definition. IIUC, does this error signify that we should not add more if-else or any other branched code in this method than it already has? Reading more about it.

2021-12-19 09:43 UTC, ShimShtein commented on yupana/processor/report_slice_processor.py
> +                            'key': 'installed_packages_mac_nics',
Instead of a single tag, let's split it into two, according to the actual transformation:

``` python
#after
                         del host['system_profile']['installed_packages']
#add
host['tags'].append({ namespace: 'report_slice_preprocessor', 'key': 'package_list_truncated', 'value': 'True'})
```

and when truncating nics:
``` python
#after
host['system_profile']['network_interfaces'] = list({nic['name']: nic for nic in host['system_profile']['network_interfaces']}.values())
#add
host['tags'].append({ namespace: 'report_slice_preprocessor', 'key': 'nics_list_truncated', 'value': 'True'})
```

Notice that tags are visible to customers, hence they need to be quite simple for understanding.

2021-12-20 17:22 UTC, apuntamb commented on yupana/processor/report_slice_processor.py
> +                            'key': 'installed_packages_mac_nics',
true, done

2021-12-20 17:24 UTC, apuntamb commented on yupana/processor/report_slice_processor.py
> +                while len(host_request_size) >= KAFKA_PRODUCER_OVERRIDE_MAX_REQUEST_SIZE:
@kgaikwad @ShimShtein let me know if you guys feel that `while` is too expensive to be used here.

2021-12-20 18:47 UTC, kgaikwad commented
> `Too many branches (16/12) (too-many-branches)`

I hope this will be helpful - https://pycodequ.al/docs/pylint-messages/r0912-too-many-branches.html

2021-12-21 08:41 UTC, kgaikwad requested changes
@apuntamb - added two inline comments.

2021-12-21 08:41 UTC, kgaikwad commented on yupana/processor/report_slice_processor.py
> +                truncate_count += 1
@apuntamb - 
Both fields i.e `mac_addresses` and `network_interfaces` anyway include invalid values which needs to be fixed.  Yupana is already transforming these fields for each host object so does it make more sense to fix these fields there.
Reference - https://github.com/quipucords/yupana/blob/master/yupana/processor/report_slice_processor.py#L463
Any thoughts?

2021-12-21 08:41 UTC, kgaikwad commented on yupana/processor/report_slice_processor.py
> +                truncate_count += 1
@ShimShtein  - Do we really need to introduce new tags for `mac_addresses` and `network_interfaces` field?
As these fields include duplicate entries I would prefer to introduce new tag only in case of truncating `installed_packages` field.

2021-12-21 08:52 UTC, ShimShtein commented on yupana/processor/report_slice_processor.py
> +                truncate_count += 1
We don't have to. A log message would suffice.

2021-12-21 08:57 UTC, ShimShtein commented on yupana/processor/report_slice_processor.py
> +            elif truncate_count == 1:
I think it would be better to keep the list sizes in sync - if you are deduping the mac addresses, it makes sense to also dedup the network interfaces.

2021-12-21 12:41 UTC, apuntamb commented on yupana/processor/report_slice_processor.py
> +                truncate_count += 1
done

2021-12-21 13:06 UTC, kgaikwad requested changes
@apuntamb  - Added few suggestions based new updated changes. Overall looks good to me.

2021-12-21 13:06 UTC, kgaikwad commented on yupana/processor/report_slice_processor.py
> +        filtered_nics = list({nic['name']: nic for nic in filtered_nics}.values())
Will it be good to move this line before filtering the `network_interfaces` based on nic > `name`?

2021-12-21 13:08 UTC, ShimShtein commented
LGTM

2021-12-21 13:09 UTC, ShimShtein commented on yupana/processor/report_slice_processor.py
> +        filtered_nics = list({nic['name']: nic for nic in filtered_nics}.values())
The previous filter removes nics without names. IMHO, there is no huge difference

2021-12-21 13:20 UTC, apuntamb commented on yupana/processor/report_slice_processor.py
> +        filtered_nics = list({nic['name']: nic for nic in filtered_nics}.values())
@kgaikwad I tried doing it before filtering, but I think there are some nics which do not have `name` property. If that's true, it gives an exception related to the `name`.

2021-12-21 13:29 UTC, apuntamb commented on yupana/processor/report_slice_processor.py
> +            del host['mac_addresses']
done

2021-12-21 13:31 UTC, kgaikwad commented on yupana/processor/report_slice_processor.py
> +        filtered_nics = list({nic['name']: nic for nic in filtered_nics}.values())
@ShimShtein - it is possible to have nic without `name` property?

2021-12-21 13:51 UTC, gnurag commented on yupana/processor/report_slice_processor.py
> +        filtered_nics = list({nic['name']: nic for nic in filtered_nics}.values())
As far as I know, on a linux system every network interface must have a name.

2021-12-21 13:56 UTC, kgaikwad commented on yupana/processor/report_slice_processor.py
> +        filtered_nics = list({nic['name']: nic for nic in filtered_nics}.values())
@ShimShtein - There won't be huge difference. 
I just wanted to avoid situation for example - 
When there are nics (100 with 90 as duplicate values) then both filtering will get apply for 100 elements. 
If we move this line above then it will filter out duplicate entries first and nics will contain just 10 and filtering will get apply for 10 elements and not on 100.
But this is ONLY applicable when every nic object contains `name` property always.

I am OK to keep this line as it is.

2021-12-21 13:59 UTC, kgaikwad approved these changes
Merging this PR!

2021-12-21 14:00 UTC, apuntamb commented on yupana/processor/report_slice_processor.py
> +        """Remove empty 'mac_addresses' field."""
done. modified method name

2021-12-21 14:00 UTC, merged

2021-12-21 14:00 UTC, kgaikwad commented
Thank you @apuntamb, @ShimShtein and @gnurag for review!