YUPANA-113 - remove duplicate entries from ip_addresses
quipucords/yupana pull request #402
Opened 2022-07-20 08:25 UTC by kgaikwad

2022-07-25 14:17 UTC, kgaikwad commented
+ adding [ShimShtein](https://github.com/ShimShtein) into loop for review.

2022-07-26 05:49 UTC, patilsuraj767 commented on yupana/processor/report_slice_processor.py
> +        if ip_addresses:
```suggestion
        if ip_addresses is None or len(x) == len(set(x)): 
            return [host, transformed_obj]
        else:
```
Let us first check if list in unique, this way transformed_obj is only appended if ip_address list is really modified.

2022-08-02 06:34 UTC, ShimShtein requested changes
Nitpick: can we rename the method? I think `remove_empty_ip_addresses` no longer suits the actual work.
I suggest `transform_ip_addresses`

2022-08-02 06:47 UTC, kgaikwad commented
> Nitpick: can we rename the method? I think `remove_empty_ip_addresses` no longer suits the actual work. I suggest `transform_ip_addresses`

@ShimShtein - Yeah, make sense. Fixed.

2022-08-02 08:01 UTC, ShimShtein approved these changes
LGTM

2022-08-02 09:31 UTC, r14chandra approved these changes
LGTM! 👍🏻

2022-08-02 09:47 UTC, merged

2022-08-02 09:47 UTC, kgaikwad commented
Thanks @ShimShtein and @r14chandra for review!