YUPANA-121 - omit nics with name cali* & its mac_addresses
quipucords/yupana pull request #409
Opened 2022-09-01 18:25 UTC by kgaikwad

2022-09-02 06:30 UTC, kgaikwad commented
+ adding [ShimShtein](https://github.com/ShimShtein) into loop for review.

2022-09-02 06:36 UTC, r14chandra commented on yupana/processor/report_slice_processor.py
> +        return [host, transformed_obj]
I'm just wondering on what condittion this last `return` stmt would hit. As all the conditions are handle in both the `if` statements.

2022-09-04 10:36 UTC, ShimShtein requested changes

2022-09-04 10:36 UTC, ShimShtein commented on yupana/processor/report_slice_processor.py
> +                if any(map(lowercase_name.__contains__,
This will remove also interface called `alcaline`. Maybe we should be a bit more strict with the pattern

2022-09-05 07:58 UTC, kgaikwad commented on yupana/processor/report_slice_processor.py
> +                if any(map(lowercase_name.__contains__,
@ShimShtein - Added a condition which will only check nic's name starts with `cali`. does it make sense or any other pattern I should check for?

2022-09-05 09:49 UTC, ShimShtein commented on yupana/processor/report_slice_processor.py
> +                if any(map(lowercase_name.__contains__,
This will solve our current problem.
If we want to be thorough, the default list of ignored interfaces in foreman is here: https://github.com/theforeman/foreman/blob/b6e40b9ac391457e7e7e7ae8f254586457d4d716/app/registries/foreman/settings/facts.rb#L21

I don't think we should add them at the moment, since they should be filtered by default.

2022-09-05 10:32 UTC, kgaikwad commented on yupana/processor/report_slice_processor.py
> +                if any(map(lowercase_name.__contains__,
Thank you @ShimShtein for confirming the changes. Merging this PR.

2022-09-05 10:36 UTC, r14chandra approved these changes
LGTM! 👍🏻

2022-09-05 11:07 UTC, merged