Refs #YUPANA-120 - Create cacert file for managed kafka
quipucords/yupana pull request #410
Opened 2022-09-16 08:21 UTC by patilsuraj767

2022-09-16 13:33 UTC, kgaikwad requested changes

2022-09-16 13:33 UTC, kgaikwad commented on yupana/processor/report_processor.py
> +            sasl_plain_username=self.kafka_ssl.get('sasl_plain_username', None),
@patilsuraj767  - Will it make sense to handle these default values assignment inside `kafka_ssl_config` method?
In that way, one can then directly pass `**kafka_ssl` to AIOKafkaProducer and no need to handle these values separately everywhere?

2022-09-20 13:04 UTC, kgaikwad commented on yupana/config/settings/base.py
> +                "security_protocol": getattr(KAFKA_BROKER.sasl, 'securityProtocol', 'PLAINTEXT'),
Do you want to set default values of sasl related keys inside `if` loop?

2022-09-21 05:27 UTC, patilsuraj767 commented on yupana/config/settings/base.py
> +                "security_protocol": getattr(KAFKA_BROKER.sasl, 'securityProtocol', 'PLAINTEXT'),
Yes, I want that sasl values to get set to default when not provided by clowder. It should not be None or null. 
In case if condition does not run then anyhow aiokafka will consider the default values for ssl.

2022-09-21 08:32 UTC, kgaikwad approved these changes

2022-09-21 08:32 UTC, merged