WIP: Yupana resiliency
quipucords/yupana pull request #85
Opened 2019-02-28 21:15 UTC by abaiken

Closes #68 
Closes #69 
Closes #70 

TODO: 
 - improve logging 
 - manual tests & unit tests

2019-03-01 15:05 UTC, myersCody commented on yupana/processor/tests_kafka_msg_handler.py
> +        self.assertEqual(self.processor.report_id, None)
You could throw the variables in a list and loop through them to make it easier to update in the future. Just a suggestion not a blocker. 

```
vars = [self.processor.report_id, self.processor.report]
for var in vars:
   self.assertEqual(var, None)
```

2019-03-01 15:12 UTC, abaiken commented on yupana/processor/kafka_msg_handler.py
> +            if retry is not None:
no these cannot because i want to avoid the else in the case that retry is False. There is the case that it is `True` in which we add, the case in which it is `None` where we reset, and the case where it is `False`, where we leave the retry as is.

2019-03-01 15:15 UTC, abaiken commented on yupana/processor/kafka_msg_handler.py
> +        :param cause: <str> should be 'VERIFICATION" or 'UPLOAD'
Good catch. And i don't think we need validation but i can make the two choices constants

2019-03-01 15:23 UTC, myersCody commented on yupana/processor/kafka_msg_handler.py
> +            if retry is not None:
OHHH that makes sense.

2019-03-01 15:28 UTC, abaiken commented on yupana/processor/kafka_msg_handler.py
> +        self.new_state = None
fixed

2019-03-01 15:29 UTC, abaiken commented on yupana/processor/kafka_msg_handler.py
> +        """Generate hosts that only failed upload to retry."""
fixed

2019-03-01 15:29 UTC, abaiken commented on yupana/processor/kafka_msg_handler.py
> +    def generate_retry_candidates(self):
fixed

2019-03-11 14:00 UTC, kholdaway requested changes
This looks really good.  Just a few small changes.

2019-03-11 14:12 UTC, kholdaway commented on yupana/processor/report_processor.py
> +RETRY = Enum('RETRY', 'clear increment archive')
Let's rename `archive` to `keep_same`

2019-03-11 14:37 UTC, kholdaway commented on yupana/processor/report_processor.py
> +        for host in candidate_hosts:
This could be a list comprehension.

2019-03-11 14:39 UTC, kholdaway commented on yupana/processor/report_processor.py
> +                    if str(response.status_code).startswith('5'):
Put a nice comment here.

2019-03-11 20:03 UTC, myersCody approved these changes

2019-03-11 20:42 UTC, kholdaway approved these changes

2019-03-11 20:43 UTC, kholdaway commented
Nice work Ashley!  🌟

2019-03-11 20:44 UTC, merged